from django.core.management.base import BaseCommand

from apps.core.models import Project

PROJECTS = [
    {
        'slug': 'yevlax-olimpiya',
        'title': 'Yevlax Olimpiya Kompleksi',
        'description': 'Fasad və təmir işləri',
        'status': 'done',
        'category': 'gov',
        'location': 'Yevlax',
        'area': '',
        'is_featured': True,
        'featured_description': 'Dövlət əhəmiyyətli layihə. Fasad və tam təmir işləri.',
        'order': 1,
    },
    {
        'slug': 'qebele-olimpiya',
        'title': 'Qəbələ Olimpiya Kompleksi',
        'description': 'Fasad və təmir işləri',
        'status': 'done',
        'category': 'gov',
        'location': 'Qəbələ',
        'area': '',
        'is_featured': False,
        'featured_description': '',
        'order': 2,
    },
    {
        'slug': 'mrt-hotel',
        'title': 'MRT Hotel',
        'description': 'Mingəçevir',
        'status': 'done',
        'category': 'com',
        'location': 'Mingəçevir',
        'area': '',
        'is_featured': False,
        'featured_description': '',
        'order': 3,
    },
    {
        'slug': 'qarabag-market',
        'title': 'Qarabağ Market',
        'description': 'Mingəçevir',
        'status': 'done',
        'category': 'com',
        'location': 'Mingəçevir',
        'area': '',
        'is_featured': False,
        'featured_description': '',
        'order': 4,
    },
    {
        'slug': 'ferdi-yasayis-evi',
        'title': 'Fərdi yaşayış evi',
        'description': 'Yevlax, Salahlı · 240 kv.m',
        'status': 'done',
        'category': 'res',
        'location': 'Yevlax, Salahlı',
        'area': '240 kv.m',
        'is_featured': False,
        'featured_description': '',
        'order': 5,
    },
    {
        'slug': '2-mertebeli-yasayis-evi',
        'title': '2 mərtəbəli yaşayış evi',
        'description': '232 kv.m · 5 otaq',
        'status': 'on',
        'category': 'res',
        'location': '',
        'area': '232 kv.m · 5 otaq',
        'is_featured': False,
        'featured_description': '',
        'order': 6,
    },
    {
        'slug': 'ticaret-eylence-kompleksi',
        'title': 'Ticarət və əyləncə kompleksi',
        'description': 'Yevlax',
        'status': 'done',
        'category': 'com',
        'location': 'Yevlax',
        'area': '',
        'is_featured': False,
        'featured_description': '',
        'order': 7,
    },
    {
        'slug': 'usaq-parki',
        'title': 'Uşaq parkı',
        'description': 'Yevlax',
        'status': 'done',
        'category': 'pub',
        'location': 'Yevlax',
        'area': '',
        'is_featured': False,
        'featured_description': '',
        'order': 8,
    },
    {
        'slug': 'ticaret-obyekti-terter',
        'title': 'Tərtər Mağaza Layihəsi',
        'description': 'Tamamlanmamış binadan müasir və funksional mağazaya çevrilmə layihəsi.',
        'status': 'done',
        'category': 'com',
        'location': 'Tərtər',
        'area': '',
        'is_featured': False,
        'featured_description': '',
        'order': 9,
    },
    {
        'slug': 'mrt-insaat-merkezi',
        'title': 'MRT İnşaat Mərkəzi',
        'description': 'Şəhərin iqtisadi və sosial inkişafına töhfə verən müasir tikinti mərkəzi.',
        'status': 'done',
        'category': 'com',
        'location': 'Mingəçevir',
        'area': '',
        'is_featured': False,
        'featured_description': '',
        'order': 10,
    },
    {
        'slug': 'istanbul-mall',
        'title': 'İstanbul Mall',
        'description': 'Yevlaxda yeni üslubda fəaliyyətə başlayan ticarət kompleksi.',
        'status': 'done',
        'category': 'com',
        'location': 'Yevlax',
        'area': '',
        'is_featured': False,
        'featured_description': '',
        'order': 11,
    },
    {
        'slug': 'ruzetam-usaq-merkezi',
        'title': 'Ruzetam Uşaq Əyləncə Mərkəzi',
        'description': 'Əvvəlki univermaq ərazisində açılan uşaq əyləncə mərkəzi — Yevlax.',
        'status': 'done',
        'category': 'com',
        'location': 'Yevlax',
        'area': '',
        'is_featured': False,
        'featured_description': '',
        'order': 12,
    },
    {
        'slug': 'kanon-aptek',
        'title': 'Kanon Aptek (keçmiş Saliton)',
        'description': 'Yevlaxda tanınan obyektin müştərinin istəyinə uyğun təmir və dizayn edilməsi.',
        'status': 'done',
        'category': 'com',
        'location': 'Yevlax',
        'area': '',
        'is_featured': False,
        'featured_description': '',
        'order': 13,
    },
    {
        'slug': 'vip-avto-yuma-kafe',
        'title': 'VIP Avtomobil Yuma və Kafe',
        'description': 'Köhnə obyektin VIP avtomobil yuma və kafe formatında canlandırılması.',
        'status': 'done',
        'category': 'com',
        'location': 'Mingəçevir',
        'area': '',
        'is_featured': False,
        'featured_description': '',
        'order': 14,
    },
    {
        'slug': 'hesenoglu-insaat',
        'title': 'Həsənoğlu İnşaat — Dizayn və Fasad',
        'description': 'Həsənoğlu İnşaat ilə birgə icra olunan dizayn və fasad işləri.',
        'status': 'done',
        'category': 'com',
        'location': '',
        'area': '',
        'is_featured': False,
        'featured_description': '',
        'order': 15,
    },
    {
        'slug': 'araz-mini-market',
        'title': 'Araz Mini Market',
        'description': 'Sıfırdan tikilən market layihəsi — Mingəçevir, Qrəs.',
        'status': 'done',
        'category': 'com',
        'location': 'Mingəçevir, Qrəs',
        'area': '',
        'is_featured': False,
        'featured_description': '',
        'order': 16,
    },
    {
        'slug': 'teze-et-serab-evi',
        'title': 'Təzə Ət və Şərab Evi',
        'description': 'Ağdaş, Ləki qəsəbəsində fərqli konseptlərlə icra edilən layihələr.',
        'status': 'done',
        'category': 'com',
        'location': 'Ağdaş, Ləki',
        'area': '',
        'is_featured': False,
        'featured_description': '',
        'order': 17,
    },
    {
        'slug': 'yevlax-heyet-evi',
        'title': 'Yevlax Həyət Evi',
        'description': 'Tikinti, təmir, fasad və memarlıq dizaynı tam peşəkar yanaşma ilə icra olunub.',
        'status': 'done',
        'category': 'res',
        'location': 'Yevlax',
        'area': '',
        'is_featured': False,
        'featured_description': '',
        'order': 18,
    },
    {
        'slug': 'mingechevir-yasayis-evi-eksteryer',
        'title': 'Mingəçevir Yaşayış Evi — Eksteryer',
        'description': 'Neoklassik üslubda eksteryer dizayn nümunəsi.',
        'status': 'done',
        'category': 'res',
        'location': 'Mingəçevir',
        'area': '',
        'is_featured': False,
        'featured_description': '',
        'order': 19,
    },
    {
        'slug': 'mingechevir-hall-temir',
        'title': 'Mingəçevir Hall Təmir Layihəsi',
        'description': 'Hall tamamilə dəyişərək müasir məkana çevrilib.',
        'status': 'done',
        'category': 'res',
        'location': 'Mingəçevir',
        'area': '',
        'is_featured': False,
        'featured_description': '',
        'order': 20,
    },
    {
        'slug': 'lenkeran-yasayis-binasi',
        'title': 'Lənkəran Yaşayış Binası',
        'description': 'Lənkəranın mərkəzində layihələndirmə və dizayn xidməti göstərilmiş müasir yaşayış binası.',
        'status': 'done',
        'category': 'res',
        'location': 'Lənkəran',
        'area': '',
        'is_featured': False,
        'featured_description': '',
        'order': 21,
    },
    {
        'slug': 'mingechevir-fasad-yenileme',
        'title': 'Mingəçevir Fasad Yeniləmə',
        'description': 'Şüşə və metal detallar vasitəsilə obyekt müasir görünüşə qovuşdurulub.',
        'status': 'done',
        'category': 'pub',
        'location': 'Mingəçevir',
        'area': '',
        'is_featured': False,
        'featured_description': '',
        'order': 22,
    },
]


class Command(BaseCommand):
    help = 'Seed Project data'

    def handle(self, *args, **options):
        for data in PROJECTS:
            obj, created = Project.objects.update_or_create(
                slug=data['slug'],
                defaults=data,
            )
            status = 'CREATED' if created else 'UPDATED'
            self.stdout.write(f'  {status}: {obj.title}')
        self.stdout.write(self.style.SUCCESS(f'Done – {len(PROJECTS)} projects.'))
