# Generated by Django 5.2.13 on 2026-04-16 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('haqqimizda', 'Haqqımızda'), ('komandamiz', 'Komandamız'), ('xidmetler', 'Xidmətlər'), ('layiheler', 'Layihələr'), ('ustunlukler', 'Üstünlüklər'), ('terefdashlar', 'Tərəfdaşlar'), ('karyera', 'Karyera'), ('xeberler', 'Xəbərlər'), ('elaqe', 'Əlaqə'), ('gizlilik', 'Gizlilik'), ('shertler', 'Şərtlər'), ('xeber-1', 'Xəbər 1'), ('xeber-2', 'Xəbər 2'), ('xeber-3', 'Xəbər 3')], max_length=32, unique=True, verbose_name='Səhifə')),
                ('tag', models.CharField(blank=True, max_length=100, verbose_name='Tag')),
                ('title', models.CharField(max_length=200, verbose_name='Başlıq (H1)')),
                ('description', models.TextField(blank=True, verbose_name='Açıqlama')),
                ('background', models.ImageField(blank=True, null=True, upload_to='heroes/', verbose_name='Fon şəkli')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Səhifə Hero',
                'verbose_name_plural': 'Səhifə Hero-lar',
                'ordering': ['page'],
            },
        ),
    ]
