# Generated by Django 5.2.13 on 2026-04-16 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagehero',
            name='meta_description',
            field=models.TextField(blank=True, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='pagehero',
            name='meta_keywords',
            field=models.TextField(blank=True, verbose_name='Meta Keywords'),
        ),
        migrations.AddField(
            model_name='pagehero',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Meta Title'),
        ),
    ]
