# Generated by Django 6.0.4 on 2026-04-17 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pagehero_meta_description_pagehero_meta_keywords_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True, verbose_name='Slug')),
                ('icon', models.CharField(help_text='Məs: fas fa-drafting-compass', max_length=100, verbose_name='İkon (FA class)')),
                ('title', models.CharField(max_length=200, verbose_name='Başlıq')),
                ('short_description', models.TextField(verbose_name='Qısa açıqlama (ana səhifə)')),
                ('description', models.TextField(verbose_name='Ətraflı açıqlama (xidmətlər səhifəsi)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Şəkil')),
                ('category_name', models.CharField(blank=True, help_text='Məs: Xidmətə daxildir, Üslublar', max_length=100, verbose_name='Kateqoriya adı')),
                ('category_items', models.TextField(blank=True, help_text='Kateqoriya altındakı mətn', verbose_name='Kateqoriya elementləri')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
            ],
            options={
                'verbose_name': 'Xidmət',
                'verbose_name_plural': 'Xidmətlər',
                'ordering': ['order'],
            },
        ),
    ]
