# Generated by Django 6.0.4 on 2026-04-17 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=128, unique=True, verbose_name='Slug')),
                ('title', models.CharField(max_length=200, verbose_name='Başlıq')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Qısa açıqlama')),
                ('status', models.CharField(choices=[('done', 'Tamamlanmış'), ('on', 'Cari')], default='done', max_length=10, verbose_name='Status')),
                ('category', models.CharField(choices=[('gov', 'Dövlət'), ('com', 'Kommersiya'), ('res', 'Yaşayış'), ('pub', 'İctimai')], default='com', max_length=10, verbose_name='Kateqoriya')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Şəkil')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Məkan')),
                ('area', models.CharField(blank=True, help_text='Məs: 240 kv.m · 5 otaq', max_length=100, verbose_name='Sahə / ölçü')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Seçilmiş layihə (mega menu)')),
                ('featured_description', models.TextField(blank=True, help_text='Mega menuda göstəriləcək açıqlama', verbose_name='Seçilmiş layihə açıqlaması')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
            ],
            options={
                'verbose_name': 'Layihə',
                'verbose_name_plural': 'Layihələr',
                'ordering': ['order'],
            },
        ),
    ]
