# Generated by Django 6.0.4 on 2026-04-17 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Başlıq')),
                ('item_type', models.CharField(choices=[('img', 'Şəkil'), ('video', 'Video')], default='img', max_length=10, verbose_name='Növ')),
                ('image', models.ImageField(blank=True, help_text='Şəkil növü üçün yüklə', null=True, upload_to='gallery/', verbose_name='Şəkil')),
                ('video_url', models.URLField(blank=True, help_text='YouTube embed link, məs: https://www.youtube.com/embed/VIDEO_ID', verbose_name='Video URL (embed)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
            ],
            options={
                'verbose_name': 'Qalereya elementi',
                'verbose_name_plural': 'Qalereya',
                'ordering': ['order'],
            },
        ),
    ]
