# Generated by Django 6.0.4 on 2026-04-17 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_galleryitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(default='Haqqımızda', max_length=100, verbose_name='Tag (ana səhifə)')),
                ('title', models.CharField(default='Gələcəyi inşa edirik', max_length=200, verbose_name='Başlıq (ana səhifə)')),
                ('summary_p1', models.TextField(verbose_name='Ana səhifə — abzas 1')),
                ('summary_p2', models.TextField(verbose_name='Ana səhifə — abzas 2')),
                ('badge1_number', models.CharField(default='500+', max_length=20, verbose_name='Badge 1 rəqəm')),
                ('badge1_label', models.CharField(default='Layihə', max_length=50, verbose_name='Badge 1 etiket')),
                ('badge2_number', models.CharField(default='4', max_length=20, verbose_name='Badge 2 rəqəm')),
                ('badge2_label', models.CharField(default='Ofis', max_length=50, verbose_name='Badge 2 etiket')),
                ('badge3_number', models.CharField(default='100+', max_length=20, verbose_name='Badge 3 rəqəm')),
                ('badge3_label', models.CharField(default='Əməkdaş', max_length=50, verbose_name='Badge 3 etiket')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='Şəkil')),
                ('profile_tag', models.CharField(default='Profil', max_length=100, verbose_name='Profil tag')),
                ('profile_title', models.CharField(default='Şirkət profili', max_length=200, verbose_name='Profil başlıq')),
                ('profile_text', models.TextField(verbose_name='Profil mətni (HTML / paraqraflar)')),
                ('values_tag', models.CharField(default='Dəyərlər', max_length=100, verbose_name='Dəyərlər tag')),
                ('values_title', models.CharField(default='Dəyərlərimiz', max_length=200, verbose_name='Dəyərlər başlıq')),
                ('values_text', models.TextField(verbose_name='Dəyərlər mətni')),
                ('vm_tag', models.CharField(default='Hədəflər', max_length=100, verbose_name='Baxış/Missiya tag')),
                ('vm_title', models.CharField(default='Baxışımız və missiyamız', max_length=200, verbose_name='Baxış/Missiya başlıq')),
                ('vision_title', models.CharField(default='Baxışımız', max_length=100, verbose_name='Baxış başlıq')),
                ('vision_text', models.TextField(verbose_name='Baxış mətni')),
                ('mission_title', models.CharField(default='Missiyamız', max_length=100, verbose_name='Missiya başlıq')),
                ('mission_text', models.TextField(verbose_name='Missiya mətni')),
                ('mega_description', models.CharField(default='2017-ci ildən fəaliyyət, 500+ layihə.', max_length=200, verbose_name='Mega menu açıqlaması')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Haqqımızda məzmunu',
                'verbose_name_plural': 'Haqqımızda məzmunu',
            },
        ),
    ]
