# Generated by Django 6.0.4 on 2026-04-17 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_aboutcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutcontent',
            name='badge1_label',
            field=models.CharField(blank=True, max_length=50, verbose_name='Badge 1 etiket'),
        ),
        migrations.AlterField(
            model_name='aboutcontent',
            name='badge1_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Badge 1 rəqəm'),
        ),
        migrations.AlterField(
            model_name='aboutcontent',
            name='badge2_label',
            field=models.CharField(blank=True, max_length=50, verbose_name='Badge 2 etiket'),
        ),
        migrations.AlterField(
            model_name='aboutcontent',
            name='badge2_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Badge 2 rəqəm'),
        ),
        migrations.AlterField(
            model_name='aboutcontent',
            name='badge3_label',
            field=models.CharField(blank=True, max_length=50, verbose_name='Badge 3 etiket'),
        ),
        migrations.AlterField(
            model_name='aboutcontent',
            name='badge3_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Badge 3 rəqəm'),
        ),
        migrations.AlterField(
            model_name='aboutcontent',
            name='mega_description',
            field=models.CharField(blank=True, max_length=200, verbose_name='Mega menu açıqlaması'),
        ),
        migrations.AlterField(
            model_name='aboutcontent',
            name='mission_title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Missiya başlıq'),
        ),
        migrations.AlterField(
            model_name='aboutcontent',
            name='profile_tag',
            field=models.CharField(blank=True, max_length=100, verbose_name='Profil tag'),
        ),
        migrations.AlterField(
            model_name='aboutcontent',
            name='profile_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Profil başlıq'),
        ),
        migrations.AlterField(
            model_name='aboutcontent',
            name='tag',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tag (ana səhifə)'),
        ),
        migrations.AlterField(
            model_name='aboutcontent',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Başlıq (ana səhifə)'),
        ),
        migrations.AlterField(
            model_name='aboutcontent',
            name='values_tag',
            field=models.CharField(blank=True, max_length=100, verbose_name='Dəyərlər tag'),
        ),
        migrations.AlterField(
            model_name='aboutcontent',
            name='values_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Dəyərlər başlıq'),
        ),
        migrations.AlterField(
            model_name='aboutcontent',
            name='vision_title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Baxış başlıq'),
        ),
        migrations.AlterField(
            model_name='aboutcontent',
            name='vm_tag',
            field=models.CharField(blank=True, max_length=100, verbose_name='Baxış/Missiya tag'),
        ),
        migrations.AlterField(
            model_name='aboutcontent',
            name='vm_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Baxış/Missiya başlıq'),
        ),
    ]
