# Generated by Django 6.0.4 on 2026-04-17 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_aboutcontent_badge1_label_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlıq')),
                ('vacancy_type', models.CharField(choices=[('job', 'Vakansiya'), ('intern', 'Təcrübə proqramı')], default='job', max_length=10, verbose_name='Növ')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Məkan')),
                ('work_type', models.CharField(blank=True, help_text='Məs: Tam ştat, Layihə əsaslı', max_length=100, verbose_name='İş rejimi')),
                ('description', models.TextField(verbose_name='Açıqlama')),
                ('whatsapp_text', models.CharField(blank=True, help_text='URL encode olunmamış mətn', max_length=300, verbose_name='WhatsApp mesaj mətni')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
            ],
            options={
                'verbose_name': 'Vakansiya',
                'verbose_name_plural': 'Vakansiyalar',
                'ordering': ['order'],
            },
        ),
    ]
