# Generated by Django 6.0.4 on 2026-04-17 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_vacancy'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('title', models.CharField(max_length=300, verbose_name='Başlıq')),
                ('tag', models.CharField(blank=True, max_length=100, verbose_name='Tag / Kateqoriya')),
                ('date_label', models.CharField(blank=True, help_text='Məs: Aprel 2026, 2025', max_length=100, verbose_name='Tarix etiketi')),
                ('short_description', models.CharField(blank=True, max_length=500, verbose_name='Qısa açıqlama')),
                ('content', models.TextField(blank=True, verbose_name='Tam məzmun (HTML)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Şəkil')),
                ('video_url', models.URLField(blank=True, verbose_name='Video URL (embed)')),
                ('is_published', models.BooleanField(default=True, verbose_name='Dərc olunub')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Xəbər',
                'verbose_name_plural': 'Xəbərlər',
                'ordering': ['order'],
            },
        ),
    ]
