# Generated by Django 6.0.4 on 2026-04-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100, verbose_name='Tag')),
                ('title', models.CharField(max_length=300, verbose_name='Başlıq')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Qısa açıqlama')),
                ('is_published', models.BooleanField(default=True, verbose_name='Dərc olunub')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
            ],
            options={
                'verbose_name': 'Bilik bazası yazısı',
                'verbose_name_plural': 'Bilik bazası',
                'ordering': ['order'],
            },
        ),
    ]
