# Generated by Django 6.0.4 on 2026-04-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_blogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100, verbose_name='Tag')),
                ('title', models.CharField(max_length=300, verbose_name='Başlıq')),
                ('description', models.CharField(max_length=500, verbose_name='Açıqlama')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'Bilik bazası',
                'verbose_name_plural': 'Bilik bazası',
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
