# Generated by Django 6.0.4 on 2026-04-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_knowledgebase_delete_blogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ad')),
                ('icon', models.CharField(help_text='Məs: fas fa-cubes', max_length=100, verbose_name='Font Awesome ikon')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Açıqlama')),
                ('category', models.CharField(choices=[('material', 'Material'), ('dovlet', 'Dövlət')], max_length=20, verbose_name='Kateqoriya')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'Tərəfdaş',
                'verbose_name_plural': 'Tərəfdaşlar',
                'ordering': ['category', 'order'],
            },
        ),
    ]
