# Generated by Django 6.0.4 on 2026-04-17 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone1', models.CharField(blank=True, max_length=30, verbose_name='Telefon 1')),
                ('phone2', models.CharField(blank=True, max_length=30, verbose_name='Telefon 2')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Ünvan')),
                ('work_hours', models.CharField(blank=True, max_length=200, verbose_name='İş saatları')),
                ('whatsapp_number', models.CharField(blank=True, help_text='Məs: 994559758900', max_length=30, verbose_name='WhatsApp nömrəsi')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram URL')),
                ('tiktok_url', models.URLField(blank=True, verbose_name='TikTok URL')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook URL')),
                ('map_embed_url', models.TextField(blank=True, verbose_name='Google Maps embed URL')),
                ('map_link', models.URLField(blank=True, verbose_name='Google Maps link')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Əlaqə məlumatları',
                'verbose_name_plural': 'Əlaqə məlumatları',
            },
        ),
        migrations.DeleteModel(
            name='Partner',
        ),
    ]
