# Generated by Django 6.0.4 on 2026-04-17 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_contactinfo_delete_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ad')),
                ('phone', models.CharField(max_length=30, verbose_name='Telefon')),
                ('project_type', models.CharField(blank=True, max_length=100, verbose_name='Növ')),
                ('message', models.TextField(blank=True, verbose_name='Mesaj')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Əlaqə müraciəti',
                'verbose_name_plural': 'Əlaqə müraciətləri',
                'ordering': ['-created_at'],
            },
        ),
    ]
