# Generated by Django 6.0.4 on 2026-04-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_contactsubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='Məs: fas fa-drafting-compass', max_length=100, verbose_name='İkon (FA class)')),
                ('title', models.CharField(max_length=200, verbose_name='Başlıq')),
                ('description', models.TextField(verbose_name='Açıqlama')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
            ],
            options={
                'verbose_name': 'Üstünlük',
                'verbose_name_plural': 'Üstünlüklər',
                'ordering': ['order'],
            },
        ),
    ]
