# Generated by Django 6.0.4 on 2026-04-17 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_advantage'),
    ]

    operations = [
    ]
