# Generated by Django 6.0.4 on 2026-04-17 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_load_advantages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='knowledgebase',
            options={'ordering': ['order'], 'verbose_name': 'Bilik bazası məqaləsi', 'verbose_name_plural': 'Bilik bazası'},
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='content',
            field=models.TextField(blank=True, verbose_name='Tam məzmun (HTML)'),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='meta_description',
            field=models.TextField(blank=True, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Meta Title'),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='description',
            field=models.CharField(max_length=500, verbose_name='Qısa açıqlama'),
        ),
    ]
