# Generated by Django 6.0.4 on 2026-04-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_knowledgebase_options_knowledgebase_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsubmission',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-poçt'),
        ),
    ]
