# Generated by Django 6.0.4 on 2026-04-17 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_contactsubmission_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactsubmission',
            name='email',
        ),
    ]
