# Generated by Django 6.0.4 on 2026-04-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_contactsubmission_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ad')),
                ('phone', models.CharField(max_length=30, verbose_name='Telefon')),
                ('area', models.CharField(blank=True, max_length=100, verbose_name='Sahə')),
                ('message', models.TextField(blank=True, verbose_name='Məlumat')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Karyera müraciəti',
                'verbose_name_plural': 'Karyera müraciətləri',
                'ordering': ['-created_at'],
            },
        ),
    ]
