# Generated by Django 6.0.4 on 2026-04-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_careerapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutcontent',
            name='badge1_label_az',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Badge 1 etiket'),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='badge1_label_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Badge 1 etiket'),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='badge1_label_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Badge 1 etiket'),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='badge2_label_az',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Badge 2 etiket'),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='badge2_label_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Badge 2 etiket'),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='badge2_label_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Badge 2 etiket'),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='badge3_label_az',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Badge 3 etiket'),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='badge3_label_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Badge 3 etiket'),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='badge3_label_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Badge 3 etiket'),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='mega_description_az',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Mega menu açıqlaması'),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='mega_description_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Mega menu açıqlaması'),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='mega_description_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Mega menu açıqlaması'),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='mission_text_az',
            field=models.TextField(null=True, verbose_name='Missiya mətni'),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='mission_text_en',
            field=models.TextField(null=True, verbose_name='Missiya mətni'),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='mission_text_ru',
            field=models.TextField(null=True, verbose_name='Missiya mətni'),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='mission_title_az',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Missiya başlıq'),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='mission_title_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Missiya başlıq'),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='mission_title_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Missiya başlıq'),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='profile_tag_az',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Profil tag'),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='profile_tag_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Profil tag'),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='profile_tag_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Profil tag'),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='profile_text_az',
            field=models.TextField(null=True, verbose_name='Profil mətni (HTML / paraqraflar)'),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='profile_text_en',
            field=models.TextField(null=True, verbose_name='Profil mətni (HTML / paraqraflar)'),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='profile_text_ru',
            field=models.TextField(null=True, verbose_name='Profil mətni (HTML / paraqraflar)'),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='profile_title_az',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Profil başlıq'),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='profile_title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Profil başlıq'),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='profile_title_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Profil başlıq'),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='summary_p1_az',
            field=models.TextField(null=True, verbose_name='Ana səhifə — abzas 1'),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='summary_p1_en',
            field=models.TextField(null=True, verbose_name='Ana səhifə — abzas 1'),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='summary_p1_ru',
            field=models.TextField(null=True, verbose_name='Ana səhifə — abzas 1'),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='summary_p2_az',
            field=models.TextField(null=True, verbose_name='Ana səhifə — abzas 2'),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='summary_p2_en',
            field=models.TextField(null=True, verbose_name='Ana səhifə — abzas 2'),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='summary_p2_ru',
            field=models.TextField(null=True, verbose_name='Ana səhifə — abzas 2'),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='tag_az',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tag (ana səhifə)'),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='tag_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tag (ana səhifə)'),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='tag_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tag (ana səhifə)'),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='title_az',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Başlıq (ana səhifə)'),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Başlıq (ana səhifə)'),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='title_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Başlıq (ana səhifə)'),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='values_tag_az',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dəyərlər tag'),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='values_tag_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dəyərlər tag'),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='values_tag_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dəyərlər tag'),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='values_text_az',
            field=models.TextField(null=True, verbose_name='Dəyərlər mətni'),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='values_text_en',
            field=models.TextField(null=True, verbose_name='Dəyərlər mətni'),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='values_text_ru',
            field=models.TextField(null=True, verbose_name='Dəyərlər mətni'),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='values_title_az',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Dəyərlər başlıq'),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='values_title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Dəyərlər başlıq'),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='values_title_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Dəyərlər başlıq'),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='vision_text_az',
            field=models.TextField(null=True, verbose_name='Baxış mətni'),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='vision_text_en',
            field=models.TextField(null=True, verbose_name='Baxış mətni'),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='vision_text_ru',
            field=models.TextField(null=True, verbose_name='Baxış mətni'),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='vision_title_az',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Baxış başlıq'),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='vision_title_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Baxış başlıq'),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='vision_title_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Baxış başlıq'),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='vm_tag_az',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Baxış/Missiya tag'),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='vm_tag_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Baxış/Missiya tag'),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='vm_tag_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Baxış/Missiya tag'),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='vm_title_az',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Baxış/Missiya başlıq'),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='vm_title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Baxış/Missiya başlıq'),
        ),
        migrations.AddField(
            model_name='aboutcontent',
            name='vm_title_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Baxış/Missiya başlıq'),
        ),
        migrations.AddField(
            model_name='advantage',
            name='description_az',
            field=models.TextField(null=True, verbose_name='Açıqlama'),
        ),
        migrations.AddField(
            model_name='advantage',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Açıqlama'),
        ),
        migrations.AddField(
            model_name='advantage',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Açıqlama'),
        ),
        migrations.AddField(
            model_name='advantage',
            name='title_az',
            field=models.CharField(max_length=200, null=True, verbose_name='Başlıq'),
        ),
        migrations.AddField(
            model_name='advantage',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Başlıq'),
        ),
        migrations.AddField(
            model_name='advantage',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Başlıq'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='address_az',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Ünvan'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='address_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Ünvan'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='address_ru',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Ünvan'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='work_hours_az',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='İş saatları'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='work_hours_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='İş saatları'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='work_hours_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='İş saatları'),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='title_az',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Başlıq'),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Başlıq'),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='title_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Başlıq'),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='content_az',
            field=models.TextField(blank=True, null=True, verbose_name='Tam məzmun (HTML)'),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='content_en',
            field=models.TextField(blank=True, null=True, verbose_name='Tam məzmun (HTML)'),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='content_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Tam məzmun (HTML)'),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='description_az',
            field=models.CharField(max_length=500, null=True, verbose_name='Qısa açıqlama'),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='description_en',
            field=models.CharField(max_length=500, null=True, verbose_name='Qısa açıqlama'),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='description_ru',
            field=models.CharField(max_length=500, null=True, verbose_name='Qısa açıqlama'),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='meta_description_az',
            field=models.TextField(blank=True, null=True, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='meta_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='meta_description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='meta_title_az',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Meta Title'),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='meta_title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Meta Title'),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='meta_title_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Meta Title'),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='tag_az',
            field=models.CharField(max_length=100, null=True, verbose_name='Tag'),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='tag_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Tag'),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='tag_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Tag'),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='title_az',
            field=models.CharField(max_length=300, null=True, verbose_name='Başlıq'),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='title_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Başlıq'),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='title_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Başlıq'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_az',
            field=models.TextField(blank=True, null=True, verbose_name='Tam məzmun (HTML)'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_en',
            field=models.TextField(blank=True, null=True, verbose_name='Tam məzmun (HTML)'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Tam məzmun (HTML)'),
        ),
        migrations.AddField(
            model_name='news',
            name='date_label_az',
            field=models.CharField(blank=True, help_text='Məs: Aprel 2026, 2025', max_length=100, null=True, verbose_name='Tarix etiketi'),
        ),
        migrations.AddField(
            model_name='news',
            name='date_label_en',
            field=models.CharField(blank=True, help_text='Məs: Aprel 2026, 2025', max_length=100, null=True, verbose_name='Tarix etiketi'),
        ),
        migrations.AddField(
            model_name='news',
            name='date_label_ru',
            field=models.CharField(blank=True, help_text='Məs: Aprel 2026, 2025', max_length=100, null=True, verbose_name='Tarix etiketi'),
        ),
        migrations.AddField(
            model_name='news',
            name='short_description_az',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Qısa açıqlama'),
        ),
        migrations.AddField(
            model_name='news',
            name='short_description_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Qısa açıqlama'),
        ),
        migrations.AddField(
            model_name='news',
            name='short_description_ru',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Qısa açıqlama'),
        ),
        migrations.AddField(
            model_name='news',
            name='tag_az',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tag / Kateqoriya'),
        ),
        migrations.AddField(
            model_name='news',
            name='tag_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tag / Kateqoriya'),
        ),
        migrations.AddField(
            model_name='news',
            name='tag_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tag / Kateqoriya'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_az',
            field=models.CharField(max_length=300, null=True, verbose_name='Başlıq'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Başlıq'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Başlıq'),
        ),
        migrations.AddField(
            model_name='pagehero',
            name='description_az',
            field=models.TextField(blank=True, null=True, verbose_name='Açıqlama'),
        ),
        migrations.AddField(
            model_name='pagehero',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Açıqlama'),
        ),
        migrations.AddField(
            model_name='pagehero',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Açıqlama'),
        ),
        migrations.AddField(
            model_name='pagehero',
            name='meta_description_az',
            field=models.TextField(blank=True, null=True, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='pagehero',
            name='meta_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='pagehero',
            name='meta_description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='pagehero',
            name='meta_keywords_az',
            field=models.TextField(blank=True, null=True, verbose_name='Meta Keywords'),
        ),
        migrations.AddField(
            model_name='pagehero',
            name='meta_keywords_en',
            field=models.TextField(blank=True, null=True, verbose_name='Meta Keywords'),
        ),
        migrations.AddField(
            model_name='pagehero',
            name='meta_keywords_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Meta Keywords'),
        ),
        migrations.AddField(
            model_name='pagehero',
            name='meta_title_az',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Meta Title'),
        ),
        migrations.AddField(
            model_name='pagehero',
            name='meta_title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Meta Title'),
        ),
        migrations.AddField(
            model_name='pagehero',
            name='meta_title_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Meta Title'),
        ),
        migrations.AddField(
            model_name='pagehero',
            name='tag_az',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tag'),
        ),
        migrations.AddField(
            model_name='pagehero',
            name='tag_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tag'),
        ),
        migrations.AddField(
            model_name='pagehero',
            name='tag_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tag'),
        ),
        migrations.AddField(
            model_name='pagehero',
            name='title_az',
            field=models.CharField(max_length=200, null=True, verbose_name='Başlıq (H1)'),
        ),
        migrations.AddField(
            model_name='pagehero',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Başlıq (H1)'),
        ),
        migrations.AddField(
            model_name='pagehero',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Başlıq (H1)'),
        ),
        migrations.AddField(
            model_name='project',
            name='area_az',
            field=models.CharField(blank=True, help_text='Məs: 240 kv.m · 5 otaq', max_length=100, null=True, verbose_name='Sahə / ölçü'),
        ),
        migrations.AddField(
            model_name='project',
            name='area_en',
            field=models.CharField(blank=True, help_text='Məs: 240 kv.m · 5 otaq', max_length=100, null=True, verbose_name='Sahə / ölçü'),
        ),
        migrations.AddField(
            model_name='project',
            name='area_ru',
            field=models.CharField(blank=True, help_text='Məs: 240 kv.m · 5 otaq', max_length=100, null=True, verbose_name='Sahə / ölçü'),
        ),
        migrations.AddField(
            model_name='project',
            name='description_az',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Qısa açıqlama'),
        ),
        migrations.AddField(
            model_name='project',
            name='description_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Qısa açıqlama'),
        ),
        migrations.AddField(
            model_name='project',
            name='description_ru',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Qısa açıqlama'),
        ),
        migrations.AddField(
            model_name='project',
            name='featured_description_az',
            field=models.TextField(blank=True, help_text='Mega menuda göstəriləcək açıqlama', null=True, verbose_name='Seçilmiş layihə açıqlaması'),
        ),
        migrations.AddField(
            model_name='project',
            name='featured_description_en',
            field=models.TextField(blank=True, help_text='Mega menuda göstəriləcək açıqlama', null=True, verbose_name='Seçilmiş layihə açıqlaması'),
        ),
        migrations.AddField(
            model_name='project',
            name='featured_description_ru',
            field=models.TextField(blank=True, help_text='Mega menuda göstəriləcək açıqlama', null=True, verbose_name='Seçilmiş layihə açıqlaması'),
        ),
        migrations.AddField(
            model_name='project',
            name='location_az',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Məkan'),
        ),
        migrations.AddField(
            model_name='project',
            name='location_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Məkan'),
        ),
        migrations.AddField(
            model_name='project',
            name='location_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Məkan'),
        ),
        migrations.AddField(
            model_name='project',
            name='title_az',
            field=models.CharField(max_length=200, null=True, verbose_name='Başlıq'),
        ),
        migrations.AddField(
            model_name='project',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Başlıq'),
        ),
        migrations.AddField(
            model_name='project',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Başlıq'),
        ),
        migrations.AddField(
            model_name='service',
            name='category_items_az',
            field=models.TextField(blank=True, help_text='Kateqoriya altındakı mətn', null=True, verbose_name='Kateqoriya elementləri'),
        ),
        migrations.AddField(
            model_name='service',
            name='category_items_en',
            field=models.TextField(blank=True, help_text='Kateqoriya altındakı mətn', null=True, verbose_name='Kateqoriya elementləri'),
        ),
        migrations.AddField(
            model_name='service',
            name='category_items_ru',
            field=models.TextField(blank=True, help_text='Kateqoriya altındakı mətn', null=True, verbose_name='Kateqoriya elementləri'),
        ),
        migrations.AddField(
            model_name='service',
            name='category_name_az',
            field=models.CharField(blank=True, help_text='Məs: Xidmətə daxildir, Üslublar', max_length=100, null=True, verbose_name='Kateqoriya adı'),
        ),
        migrations.AddField(
            model_name='service',
            name='category_name_en',
            field=models.CharField(blank=True, help_text='Məs: Xidmətə daxildir, Üslublar', max_length=100, null=True, verbose_name='Kateqoriya adı'),
        ),
        migrations.AddField(
            model_name='service',
            name='category_name_ru',
            field=models.CharField(blank=True, help_text='Məs: Xidmətə daxildir, Üslublar', max_length=100, null=True, verbose_name='Kateqoriya adı'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_az',
            field=models.TextField(null=True, verbose_name='Ətraflı açıqlama (xidmətlər səhifəsi)'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Ətraflı açıqlama (xidmətlər səhifəsi)'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Ətraflı açıqlama (xidmətlər səhifəsi)'),
        ),
        migrations.AddField(
            model_name='service',
            name='short_description_az',
            field=models.TextField(null=True, verbose_name='Qısa açıqlama (ana səhifə)'),
        ),
        migrations.AddField(
            model_name='service',
            name='short_description_en',
            field=models.TextField(null=True, verbose_name='Qısa açıqlama (ana səhifə)'),
        ),
        migrations.AddField(
            model_name='service',
            name='short_description_ru',
            field=models.TextField(null=True, verbose_name='Qısa açıqlama (ana səhifə)'),
        ),
        migrations.AddField(
            model_name='service',
            name='title_az',
            field=models.CharField(max_length=200, null=True, verbose_name='Başlıq'),
        ),
        migrations.AddField(
            model_name='service',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Başlıq'),
        ),
        migrations.AddField(
            model_name='service',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Başlıq'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='description_az',
            field=models.TextField(null=True, verbose_name='Açıqlama'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Açıqlama'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Açıqlama'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='location_az',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Məkan'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='location_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Məkan'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='location_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Məkan'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='title_az',
            field=models.CharField(max_length=200, null=True, verbose_name='Başlıq'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Başlıq'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Başlıq'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='whatsapp_text_az',
            field=models.CharField(blank=True, help_text='URL encode olunmamış mətn', max_length=300, null=True, verbose_name='WhatsApp mesaj mətni'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='whatsapp_text_en',
            field=models.CharField(blank=True, help_text='URL encode olunmamış mətn', max_length=300, null=True, verbose_name='WhatsApp mesaj mətni'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='whatsapp_text_ru',
            field=models.CharField(blank=True, help_text='URL encode olunmamış mətn', max_length=300, null=True, verbose_name='WhatsApp mesaj mətni'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='work_type_az',
            field=models.CharField(blank=True, help_text='Məs: Tam ştat, Layihə əsaslı', max_length=100, null=True, verbose_name='İş rejimi'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='work_type_en',
            field=models.CharField(blank=True, help_text='Məs: Tam ştat, Layihə əsaslı', max_length=100, null=True, verbose_name='İş rejimi'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='work_type_ru',
            field=models.CharField(blank=True, help_text='Məs: Tam ştat, Layihə əsaslı', max_length=100, null=True, verbose_name='İş rejimi'),
        ),
    ]
