# Generated by Django 6.0.4 on 2026-04-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_aboutcontent_badge1_label_az_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube embed link, məs: https://www.youtube.com/embed/VIDEO_ID', verbose_name='Video URL (embed)'),
        ),
    ]
