# Generated by Django 6.0.4 on 2026-04-17 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_service_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='video_url',
        ),
        migrations.AddField(
            model_name='service',
            name='video',
            field=models.FileField(blank=True, help_text='MP4 video faylı yüklə', null=True, upload_to='services/videos/', verbose_name='Video (mp4)'),
        ),
    ]
