# Generated by Django 6.0.4 on 2026-04-22 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_projectimage_serviceimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ad')),
                ('name_az', models.CharField(max_length=200, null=True, verbose_name='Ad')),
                ('name_ru', models.CharField(max_length=200, null=True, verbose_name='Ad')),
                ('name_en', models.CharField(max_length=200, null=True, verbose_name='Ad')),
                ('icon', models.CharField(help_text='Font Awesome class, məs: fas fa-cubes', max_length=100, verbose_name='İkon (FA)')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Açıqlama')),
                ('description_az', models.CharField(blank=True, max_length=500, null=True, verbose_name='Açıqlama')),
                ('description_ru', models.CharField(blank=True, max_length=500, null=True, verbose_name='Açıqlama')),
                ('description_en', models.CharField(blank=True, max_length=500, null=True, verbose_name='Açıqlama')),
                ('category', models.CharField(choices=[('material', 'Material təchizatçısı'), ('dovlet', 'Dövlət əməkdaşlığı'), ('ozel', 'Özəl şirkət')], max_length=20, verbose_name='Kateqoriya')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'Tərəfdaş',
                'verbose_name_plural': 'Tərəfdaşlar',
                'ordering': ['category', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('mgmt', 'Rəhbərlik'), ('spec', 'Mütəxəssis')], default='spec', max_length=10, verbose_name='Qrup')),
                ('name', models.CharField(max_length=200, verbose_name='Ad Soyad')),
                ('name_az', models.CharField(max_length=200, null=True, verbose_name='Ad Soyad')),
                ('name_ru', models.CharField(max_length=200, null=True, verbose_name='Ad Soyad')),
                ('name_en', models.CharField(max_length=200, null=True, verbose_name='Ad Soyad')),
                ('role', models.CharField(max_length=200, verbose_name='Vəzifə')),
                ('role_az', models.CharField(max_length=200, null=True, verbose_name='Vəzifə')),
                ('role_ru', models.CharField(max_length=200, null=True, verbose_name='Vəzifə')),
                ('role_en', models.CharField(max_length=200, null=True, verbose_name='Vəzifə')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team/', verbose_name='Şəkil')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'Komanda üzvü',
                'verbose_name_plural': 'Komanda',
                'ordering': ['group', 'order', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='serviceimage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
