# Generated by Django 6.0.4 on 2026-04-23 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_projectimage_serviceimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='partners/', verbose_name='Loqo (şəkil)'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='icon',
            field=models.CharField(blank=True, help_text='Şəkil yoxdursa FA ikon, məs: fas fa-cubes', max_length=100, verbose_name='İkon (FA, ehtiyat)'),
        ),
    ]
