# Generated by Django 6.0.4 on 2026-04-23 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_merge_0026_partner_0027_add_partner_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebase',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='knowledge-base/', verbose_name='Şəkil'),
        ),
    ]
