# Generated by Django 6.0.4 on 2026-04-23 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_knowledgebase_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagehero',
            name='page',
            field=models.CharField(choices=[('haqqimizda', 'Haqqımızda'), ('komandamiz', 'Komandamız'), ('xidmetler', 'Xidmətlər'), ('layiheler', 'Layihələr'), ('ustunlukler', 'Üstünlüklər'), ('terefdashlar', 'Tərəfdaşlar'), ('karyera', 'Karyera'), ('xeberler', 'Xəbərlər'), ('bloq', 'Bloq'), ('elaqe', 'Əlaqə'), ('gizlilik', 'Gizlilik'), ('shertler', 'Şərtlər'), ('xeber-1', 'Xəbər 1'), ('xeber-2', 'Xəbər 2'), ('xeber-3', 'Xəbər 3')], max_length=32, unique=True, verbose_name='Səhifə'),
        ),
    ]
