# Generated by Django 6.0.4 on 2026-04-24 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_pagehero_video_alter_pagehero_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagehero',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Başlıq (H1)'),
        ),
        migrations.AlterField(
            model_name='pagehero',
            name='title_az',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Başlıq (H1)'),
        ),
        migrations.AlterField(
            model_name='pagehero',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Başlıq (H1)'),
        ),
        migrations.AlterField(
            model_name='pagehero',
            name='title_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Başlıq (H1)'),
        ),
    ]
