# Generated by Django 6.0.4 on 2026-04-24 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_pagehero_title_alter_pagehero_title_az_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ad')),
                ('name_az', models.CharField(max_length=100, null=True, verbose_name='Ad')),
                ('name_ru', models.CharField(max_length=100, null=True, verbose_name='Ad')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Ad')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'Kataloq kateqoriyası',
                'verbose_name_plural': 'Kataloq kateqoriyaları',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='pagehero',
            name='page',
            field=models.CharField(choices=[('home', 'Ana Səhifə'), ('haqqimizda', 'Haqqımızda'), ('komandamiz', 'Komandamız'), ('xidmetler', 'Xidmətlər'), ('layiheler', 'Layihələr'), ('ustunlukler', 'Üstünlüklər'), ('terefdashlar', 'Tərəfdaşlar'), ('karyera', 'Karyera'), ('xeberler', 'Xəbərlər'), ('bloq', 'Bloq'), ('kataloq', 'Kataloq'), ('elaqe', 'Əlaqə'), ('gizlilik', 'Gizlilik'), ('shertler', 'Şərtlər'), ('xeber-1', 'Xəbər 1'), ('xeber-2', 'Xəbər 2'), ('xeber-3', 'Xəbər 3')], max_length=32, unique=True, verbose_name='Səhifə'),
        ),
        migrations.CreateModel(
            name='CatalogImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Başlıq')),
                ('title_az', models.CharField(blank=True, max_length=200, null=True, verbose_name='Başlıq')),
                ('title_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Başlıq')),
                ('title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Başlıq')),
                ('image', models.ImageField(upload_to='catalog/images/', verbose_name='Şəkil')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='core.catalogcategory', verbose_name='Kateqoriya')),
            ],
            options={
                'verbose_name': 'Kataloq şəkli',
                'verbose_name_plural': 'Kataloq şəkilləri',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CatalogPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlıq')),
                ('title_az', models.CharField(max_length=200, null=True, verbose_name='Başlıq')),
                ('title_ru', models.CharField(max_length=200, null=True, verbose_name='Başlıq')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Başlıq')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Qısa açıqlama')),
                ('description_az', models.CharField(blank=True, max_length=300, null=True, verbose_name='Qısa açıqlama')),
                ('description_ru', models.CharField(blank=True, max_length=300, null=True, verbose_name='Qısa açıqlama')),
                ('description_en', models.CharField(blank=True, max_length=300, null=True, verbose_name='Qısa açıqlama')),
                ('file', models.FileField(upload_to='catalog/pdfs/', verbose_name='PDF faylı')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='catalog/pdf-covers/', verbose_name='Üz şəkli')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdfs', to='core.catalogcategory', verbose_name='Kateqoriya')),
            ],
            options={
                'verbose_name': 'Kataloq PDF',
                'verbose_name_plural': 'Kataloq PDF-lər',
                'ordering': ['order', 'id'],
            },
        ),
    ]
