# Generated by Django 6.0.4 on 2026-04-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_catalogcategory_alter_pagehero_page_catalogimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogpdf',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Başlıq'),
        ),
        migrations.AlterField(
            model_name='catalogpdf',
            name='title_az',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Başlıq'),
        ),
        migrations.AlterField(
            model_name='catalogpdf',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Başlıq'),
        ),
        migrations.AlterField(
            model_name='catalogpdf',
            name='title_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Başlıq'),
        ),
    ]
