# Generated by Django 6.0.4 on 2026-04-24 16:39

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_catalogpdf_title_alter_catalogpdf_title_az_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutcontent',
            name='profile_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Paraqraflar, qalın/kürsiv mətn, siyahılar dəstəklənir.', verbose_name='Profil mətni'),
        ),
        migrations.AlterField(
            model_name='aboutcontent',
            name='profile_text_az',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Paraqraflar, qalın/kürsiv mətn, siyahılar dəstəklənir.', null=True, verbose_name='Profil mətni'),
        ),
        migrations.AlterField(
            model_name='aboutcontent',
            name='profile_text_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Paraqraflar, qalın/kürsiv mətn, siyahılar dəstəklənir.', null=True, verbose_name='Profil mətni'),
        ),
        migrations.AlterField(
            model_name='aboutcontent',
            name='profile_text_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Paraqraflar, qalın/kürsiv mətn, siyahılar dəstəklənir.', null=True, verbose_name='Profil mətni'),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Zehinli redaktor — şəkil, link, sərlovhə əlavə edə bilərsiniz.', verbose_name='Tam məzmun'),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='content_az',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Zehinli redaktor — şəkil, link, sərlovhə əlavə edə bilərsiniz.', null=True, verbose_name='Tam məzmun'),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Zehinli redaktor — şəkil, link, sərlovhə əlavə edə bilərsiniz.', null=True, verbose_name='Tam məzmun'),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='content_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Zehinli redaktor — şəkil, link, sərlovhə əlavə edə bilərsiniz.', null=True, verbose_name='Tam məzmun'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Zehinli redaktor — şəkil, link, sərlovhə əlavə edə bilərsiniz.', verbose_name='Tam məzmun'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_az',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Zehinli redaktor — şəkil, link, sərlovhə əlavə edə bilərsiniz.', null=True, verbose_name='Tam məzmun'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Zehinli redaktor — şəkil, link, sərlovhə əlavə edə bilərsiniz.', null=True, verbose_name='Tam məzmun'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Zehinli redaktor — şəkil, link, sərlovhə əlavə edə bilərsiniz.', null=True, verbose_name='Tam məzmun'),
        ),
    ]
