# Generated by Django 6.0.4 on 2026-04-24 16:47

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_aboutcontent_profile_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Zehinli redaktor — qalın mətn, siyahı, link əlavə edə bilərsiniz.', verbose_name='Açıqlama'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description_az',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Zehinli redaktor — qalın mətn, siyahı, link əlavə edə bilərsiniz.', null=True, verbose_name='Açıqlama'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Zehinli redaktor — qalın mətn, siyahı, link əlavə edə bilərsiniz.', null=True, verbose_name='Açıqlama'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Zehinli redaktor — qalın mətn, siyahı, link əlavə edə bilərsiniz.', null=True, verbose_name='Açıqlama'),
        ),
        migrations.AlterField(
            model_name='project',
            name='featured_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Mega menuda göstəriləcək açıqlama', verbose_name='Seçilmiş layihə açıqlaması'),
        ),
        migrations.AlterField(
            model_name='project',
            name='featured_description_az',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Mega menuda göstəriləcək açıqlama', null=True, verbose_name='Seçilmiş layihə açıqlaması'),
        ),
        migrations.AlterField(
            model_name='project',
            name='featured_description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Mega menuda göstəriləcək açıqlama', null=True, verbose_name='Seçilmiş layihə açıqlaması'),
        ),
        migrations.AlterField(
            model_name='project',
            name='featured_description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Mega menuda göstəriləcək açıqlama', null=True, verbose_name='Seçilmiş layihə açıqlaması'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Zehinli redaktor — şəkil, link, sərlovhə, siyahı əlavə edə bilərsiniz.', verbose_name='Ətraflı açıqlama (xidmətlər səhifəsi)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description_az',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Zehinli redaktor — şəkil, link, sərlovhə, siyahı əlavə edə bilərsiniz.', null=True, verbose_name='Ətraflı açıqlama (xidmətlər səhifəsi)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Zehinli redaktor — şəkil, link, sərlovhə, siyahı əlavə edə bilərsiniz.', null=True, verbose_name='Ətraflı açıqlama (xidmətlər səhifəsi)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Zehinli redaktor — şəkil, link, sərlovhə, siyahı əlavə edə bilərsiniz.', null=True, verbose_name='Ətraflı açıqlama (xidmətlər səhifəsi)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='short_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Zehinli redaktor — qalın/kürsiv mətn, siyahı, link.', verbose_name='Qısa açıqlama (ana səhifə)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='short_description_az',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Zehinli redaktor — qalın/kürsiv mətn, siyahı, link.', null=True, verbose_name='Qısa açıqlama (ana səhifə)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='short_description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Zehinli redaktor — qalın/kürsiv mətn, siyahı, link.', null=True, verbose_name='Qısa açıqlama (ana səhifə)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='short_description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Zehinli redaktor — qalın/kürsiv mətn, siyahı, link.', null=True, verbose_name='Qısa açıqlama (ana səhifə)'),
        ),
    ]
